/** Fallback when API is unreachable — keep keys aligned with `backend/pipeline_steps.py`. */
export const PIPELINE_STEPS = [
  {
    key: "topic_card",
    label: "Topic Card",
    matrixLabel: "Plan & topic",
    matrixCol: "TC",
    index: 1,
  },
  {
    key: "serp_research",
    label: "SERP Research",
    matrixLabel: "Search landscape",
    matrixCol: "SR",
    index: 2,
  },
  {
    key: "research",
    label: "SERP Analysis & Gaps",
    matrixLabel: "Gap analysis",
    matrixCol: "SA",
    index: 3,
  },
  {
    key: "atp_topic_research",
    label: "ATP Topic Research",
    matrixLabel: "Topic questions",
    matrixCol: "ATP",
    index: 4,
  },
  {
    key: "paa_faq_research",
    label: "PAA / FAQ Research",
    matrixLabel: "FAQ questions",
    matrixCol: "FQ",
    index: 5,
  },
  {
    key: "case_study_research",
    label: "Case Study Research",
    matrixLabel: "Case study",
    matrixCol: "CS",
    index: 6,
  },
  {
    key: "research_audit",
    label: "Research Audit",
    matrixLabel: "Verify research",
    matrixCol: "RA",
    index: 7,
  },
  {
    key: "assignment_brief",
    label: "Assignment Brief",
    matrixLabel: "Editorial brief",
    matrixCol: "BR",
    index: 8,
  },
  {
    key: "outline",
    label: "Outline",
    matrixLabel: "Article outline",
    matrixCol: "OL",
    index: 9,
  },
  {
    key: "draft",
    label: "Draft",
    matrixLabel: "First draft",
    matrixCol: "DR",
    index: 10,
  },
  {
    key: "supporting_posts",
    label: "Supporting Posts",
    matrixLabel: "Cluster drafts",
    matrixCol: "SP",
    index: 11,
  },
  {
    key: "fact_check",
    label: "Fact Check (web + editor)",
    matrixLabel: "Review & accuracy",
    matrixCol: "FC",
    index: 12,
  },
  {
    key: "meta_seo",
    label: "Meta Title & Description",
    matrixLabel: "SEO meta tags",
    matrixCol: "MS",
    index: 13,
  },
  {
    key: "final_output",
    label: "Final Output",
    matrixLabel: "Ready to publish",
    matrixCol: "FO",
    index: 14,
  },
];

export const PIPELINE_STEP_KEYS = PIPELINE_STEPS.map((s) => s.key);
